apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pxazxz1ix-nodejs 
  janus-idp.io/tekton: pxazxz1ix-nodejs
  backstage.io/kubernetes-id: pxazxz1ix-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pxazxz1ix-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml