apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pxazxz1ix-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pxazxz1ix-nodejs 
  name: pxazxz1ix-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pxazxz1ix-nodejs 
